FROM openjdk:17-jdk-slim AS development

LABEL maintainer="miniyus"

WORKDIR /app

COPY build.gradle /app/build.gradle
COPY gradlew /app/gradlew
COPY src /app/src

EXPOSE 8080

ENTRYPOINT [ "./gradlew", "bootRun", "-t"]
