FROM openjdk:17-jdk-slim AS development

LABEL maintainer="miniyus"

WORKDIR /app

COPY build.gradle /app/build.gradle
COPY gradlew /app/gradlew
COPY docker-entrypoint /

RUN chmod +x /docker-entrypoint

EXPOSE 8080

ENV JAVA_OPTS=""

ENTRYPOINT ["/docker-entrypoint"]
