version: "3"
services:
    friday-api:
        container_name: friday-api
        image: friday-api:latest
        build:
            context: ./friday-api
            dockerfile: Dockerfile
            args:
                JAR_FILE: friday.jar
        ports:
            - "${API_PORT:-8080}:8080"
        depends_on:
            - friday-db
            - friday-redis
        volumes:
            - ./api/src/main/resources/:/app/resources
            - ./data/friday:/data
        networks:
            - friday
        environment:
            - APP_ENV=${APP_ENV}
            - API_URL=${API_URL}
            - API_LOG_LEVEL=${API_LOG_LEVEL}
            - JWT_SECRET=${JWT_SECRET}
            - DB_HOST=${DB_HOST:-friday-db}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - REDIS_HOST=${REDIS_HOST:-friday-redis}
            - REDIS_DATABASE=${REDIS_DATABASE}
            - REDIS_USERNAME=${REDIS_USERNAME}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
            - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
            - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
            - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
    friday-db:
        container_name: friday-db
        image: postgres:15
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - "${DB_PORT:-5432}:5432"
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}",
                ]
            retries: 3
            timeout: 5s
        networks:
            - friday
    friday-redis:
        container_name: friday-redis
        image: redis:latest
        ports:
            - "${REDIS_PORT:-6379}:6379"
        networks:
            - friday
        volumes:
            - ./data/redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    friday-ui:
        container_name: friday-ui
        image: friday-ui:latest
        build:
            context: ./friday-ui
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - friday
networks:
    friday:
        driver: bridge
