version: "3"
services:
    friday-api:
        container_name: friday-api
        image: friday-api:dev
        build:
            context: ./friday-api
            dockerfile: Dockerfile.dev
            args:
                JAR_FILE: friday.jar
        ports:
            - "8080:8080"
        depends_on:
            - friday-db
            - friday-redis
        volumes:
            - ./friday-api:/app
        networks:
            - friday
        environment:
            - APP_NAME=${APPIO_NAME:-Cuttysark APPIO}
            - APP_SECRET=${APPIO_SECRET}
            - APP_ENV=${APP_ENV}
            - APP_URL=${API_URL}
            - LOG_LEVEL=${API_LOG_LEVEL:-debug}
            - JWT_SECRET=${JWT_SECRET:-secret}
            - DB_HOST=${DB_HOST:-friday-db}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - REDIS_HOST=${REDIS_HOST:-friday-redis}
            - REDIS_DATABASE=${REDIS_DATABASE:-0}
            - REDIS_USERNAME=${REDIS_USERNAME:-}
            - REDIS_PASSWORD=${REDIS_PASSWORD:-}
            - REDIS_PORT=${REDIS_PORT:6379}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
            - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
            - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
            - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
            - JAVA_OPTS=${JAVA_OPTS:-}
    friday-db:
        container_name: friday-db
        image: postgres:15
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - "${DB_PORT:-5432}:5432"
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}",
                ]
            retries: 3
            timeout: 5s
        networks:
            - friday
    friday-redis:
        container_name: friday-redis
        image: redis:latest
        ports:
            - "${REDIS_PORT:-6379}:6379"
        networks:
            - friday
        volumes:
            - ./data/redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    friday-ui:
        container_name: friday-ui
        image: friday-ui:dev
        build:
            context: ./friday-ui
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        networks:
            - friday
        volumes:
            - ./friday-ui:/react
            - /react/node_modules
networks:
    friday:
        driver: bridge
