FROM node:20.10-alpine as build

LABEL maintainer="miniyus"

WORKDIR /react

COPY package.json .
COPY yarn.lock .
COPY .env .

RUN yarn install

COPY docker-entrypoint /

RUN chmod +x /docker-entrypoint

EXPOSE 3000

COPY . .

ENTRYPOINT [ "/docker-entrypoint" ]
