FROM node:20.10-alpine AS build

LABEL maintainer="miniyus"

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY docker-entrypoint /

RUN chmod +x /docker-entrypoint

EXPOSE 3000

ENTRYPOINT [ "/docker-entrypoint" ]
