server:
  undertow:
    threads:
      io: 2
      worker: 200
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:validate}
logging:
  level:
    root: warn
    undertow: warn
    org.springframework.web: debug
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
    org.springframework.security: debug
    org.springframework.data: debug
    org.hibernate: error
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace
    com.com.meteormin.friday: debug
    com.com.meteormin.friday.infrastructure.aspect: debug
    com.com.meteormin.friday.infrastructure.advice: debug
    com.com.meteormin.friday.infrastructure.task: debug
