spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  file:
    path: ${LOG_PATH:log}
    name: ${LOG_PATH:log}/friday-api.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH:log}/friday-api-%d{yyyy-MM-dd}.%i
  level:
    root: warn
    tomcat: warn
    org:
      springframework:
        web: ${LOG_LEVEL:debug}
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate: error
    com:
      miniyus:
        friday: ${LOG_LEVEL:debug}
