spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: testUser
        password: pass
        driverClassName: org.h2.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    redis:
        pool:
            min-idle: 0
            max-idle: 8
            max-active: 8
        host: 127.0.0.1
        port: 6379
    devtools:
        add-properties: true
        restart:
            enabled: true
logging:
    file:
        path: ${LOG_PATH:log}
        name: ${LOG_PATH:log}/friday-api.log
    logback:
        rollingpolicy:
            file-name-pattern: ${LOG_PATH:./log}/friday-api-%d{yyyy-MM-dd}.%i
    level:
        root: warn
        tomcat: warn
        org.springframework.web: ${LOG_LEVEL:debug}
        com.miniyus.friday: ${LOG_LEVEL:debug}
        org.hibernate: error
