app:
  secret: ${APP_SECRET:secret}
server:
  servlet:
    encoding:
      force-response: true
spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:tc:postgresql:16:///testDB
    username: testUser
    password: testPass
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
logging:
  level:
    root: warn
    undertow: warn
    org.springframework.web: debug
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
    org.springframework.security: debug
    org.springframework.data: debug
    org.hibernate: error
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace
    com.com.meteormin.friday: debug
    com.com.meteormin.friday.infrastructure.aspect: debug
    com.com.meteormin.friday.infrastructure.advice: debug
    com.com.meteormin.friday.infrastructure.task: debug
